frases = [
    "If you're seeking a(n) {climate} climate and {cost} cost of living, {city} in {country} offers {culture} culture and various activities.",
    "Discover the {culture} cultural treasures of {city}, a city known for its attractions, all while enjoying the {climate} weather.",
    "Experience {tourism_type} tourism in {city}, where the {climate} climate complements the {culture} culture, and delights await at every corner.",
    "Explore {city}, a gem in {country} with a {climate} climate, renowned for its {culture} culture, making it a perfect {cost} cost destination.",
    "{city} is the place to be for those fascinated by {culture} culture, all set in a {climate} climate with {cost} living expenses.",
    "Immerse yourself in the {culture} culture of {city}, {country}, where the {climate} climate is always pleasant and the food is unforgettable.",
    "For a(n) {tourism_type} escape with {cost} costs, {city} in {country} offers a unique blend of {culture} culture and {climate} weather.",
    "With its {climate} climate and {culture} cultural richness, {city} is a top choice for travelers interested in unique experiences and {language} language.",
    "Enjoy the {culture} vibes and flavors of {city}, a city that stands out in {country} for its {cost} affordability and {climate} climate.",
    "Visit {city} for an authentic {tourism_type} experience, where the {culture} culture is {culture} and the attractions reflect the {climate} climate.",
    "{city}: Where {cost} cost meets {culture} culture under the {climate} climate, offering diverse activities and speaking {language}.",
    "From its {culture} cultural heritage to its {climate} climate, {city} in {country} is a haven for foodies and adventure seekers alike.",
    "Embrace the {climate} weather and {cost} cost living in {city}, where every street corner tells a story of {culture} culture.",
    "In {city}, the {climate} climate enriches the {culture} culture, and the experiences are as diverse as the city's {tourism_type} tourism offerings.",
    "{city} invites you to explore its {culture} cultural depths, {climate} climate, and vibrant scenes, all within a {cost} budget in {country}.",
    "Experience {culture} culture and {climate} weather in {city}, {country}, offering delights at a {cost} cost, perfect for {tourism_type} lovers.",
    "Immerse yourself in the {culture} heritage and flavors of {city}, a {cost} treasure in {country} with a welcoming {climate} climate for {tourism_type} enthusiasts.",
    "{city}, a {climate} haven in {country}, boasts {culture} richness and {cost} affordability, making it an ideal {tourism_type} destination.",
    "Discover the {culture} essence and tastes of {city}, {country}, where the {climate} climate complements a {cost} lifestyle, inviting {tourism_type} tourists.",
]